# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0001_initial'),
    ]
