# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0002_auto_20180228_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7701\u4efd\u4fe1\u606f'),
        ),
    ]
