# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-12 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0003_auto_20180612_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='develop_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u73af\u5883\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f4d\u7f6e\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8fd0\u8425\u5546\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
    ]
