# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-13 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0004_auto_20180612_1941'),
    ]

