# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0005_auto_20180110_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_type',
            field=models.CharField(blank=True, choices=[('svn', 'svn'), ('git', 'git'), ('file', 'file')], max_length=255, null=True, verbose_name='\u6e90\u7c7b\u578b'),
        ),
    ]
