# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0008_auto_20180130_1028'),
    ]

    operations = [
    ]
