# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0012_auto_20180130_1417'),
    ]
    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_address',
            field=models.CharField(default='0.0.0.0', max_length=255, verbose_name='\u673a\u5668\u5730\u5740'),
            preserve_default=False,
        ),
    ]
