# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-28 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0014_auto_20180228_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='app_console_password',
        ),
        migrations.RemoveField(
            model_name='project',
            name='app_console_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='app_console_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='db_password',
        ),
        migrations.RemoveField(
            model_name='project',
            name='db_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='os_password',
        ),
        migrations.RemoveField(
            model_name='project',
            name='os_user',
        ),
    ]
