# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-28 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0016_project_app_console_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='app_console_url',
            new_name='console_url',
        ),
    ]
