# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-28 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0018_auto_20180228_1143'),
    ]

