# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0006_auto_20180110_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
