# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0007_auto_20180110_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='jmx_port',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='JMX\u670d\u52a1\u7aef\u53e3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='\u6240\u5c5e\u4e2d\u5fc3'),
        ),
    ]
