# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0009_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
