# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-30 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0010_remove_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='jmx_port',
            field=models.CharField(blank=True, default='1', max_length=255, null=True, verbose_name='JMX\u670d\u52a1\u7aef\u53e3'),
        ),
    ]
