# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-28 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='db_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u4fe1\u606f'),
        ),
    ]
