# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-06-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0002_auto_20180228_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_console_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63a7\u5236\u53f0\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='app_console_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63a7\u5236\u53f0\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='project',
            name='app_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u767b\u5f55\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='app_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u5e94\u7528URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='app_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u767b\u5f55\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='project',
            name='console_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63a7\u5236\u53f0URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='db_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='project',
            name='develop_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u73af\u5883\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='project',
            name='jmx_port',
            field=models.CharField(default='1', max_length=255, verbose_name='JMX\u670d\u52a1\u7aef\u53e3'),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u4f4d\u7f6e\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='project',
            name='operator',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u8fd0\u8425\u5546\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='project',
            name='os_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='os_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='project',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u7701\u4efd\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='project',
            name='configPath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u65e5\u5fd7\u6587\u4ef6\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appconf.Product', verbose_name='\u6240\u5c5e\u4e2d\u5fc3'),
        ),
        migrations.AlterField(
            model_name='project',
            name='server_type',
            field=models.CharField(blank=True, choices=[('Tomcat', 'Tomcat'), ('Weblogic9i', 'Weblogic9i'), ('Weblogic11g', 'Weblogic11g'), ('JETTY', 'JETTY'), ('Nginx', 'Nginx'), ('Gunicorn', 'Gunicorn'), ('Uwsgi', 'Uwsgi'), ('Apache', 'Apache'), ('IIS', 'IIS'), ('Was6', 'Was6'), ('Was7', 'Was7')], max_length=30, null=True, verbose_name='\u670d\u52a1\u5668\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_address',
            field=models.CharField(max_length=255, verbose_name='\u673a\u5668\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_type',
            field=models.CharField(blank=True, choices=[('svn', 'svn'), ('git', 'git'), ('file', 'file')], max_length=255, null=True, verbose_name='\u6e90\u7c7b\u578b'),
        ),
    ]
