# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0002_project_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u767b\u5f55\u7528\u6237\u540d'),
        ),
    ]
