# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-28 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appconf', '0013_auto_20180201_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_console_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63a7\u5236\u53f0\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='app_console_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63a7\u5236\u53f0URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='app_console_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u63a7\u5236\u53f0\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='project',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='db_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u6570\u636e\u5e93\u7528\u6237\u540d'),
        ),
        migrations.AddField(
            model_name='project',
            name='os_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u5bc6\u7801'),
        ),
        migrations.AddField(
            model_name='project',
            name='os_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='project',
            name='configPath',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='\u65e5\u5fd7\u6587\u4ef6\u8def\u5f84'),
        ),
    ]
